export const MOCK_COURSE_DATA = {
  page: 1,
  size: 25,
  lastPage: 6,
  total: 150,
  data: [
    {
      loaiMonHoc: 'Giáo dục đại cương',
      maMH: 'BAA00003',
      tenMH: 'Tư tưởng Hồ Chí Minh',
      soTinChi: 2,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Giáo dục đại cương',
      maMH: 'BAA00004',
      tenMH: 'Pháp luật đại cương',
      soTinChi: 3,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Giáo dục đại cương',
      maMH: 'BAA00021',
      tenMH: 'Thể dục 1',
      soTinChi: 2,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Giáo dục đại cương',
      maMH: 'BAA00022',
      tenMH: 'Thể dục 2',
      soTinChi: 2,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Giáo dục đại cương',
      maMH: 'BAA00101',
      tenMH: 'Triết học Mác-Lênin',
      soTinChi: 2,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Giáo dục đại cương',
      maMH: 'BAA00102',
      tenMH: 'Kinh tế chính trị Mác - Lênin',
      soTinChi: 2,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Giáo dục đại cương',
      maMH: 'BAA00103',
      tenMH: 'Chủ nghĩa xã hội khoa học',
      soTinChi: 2,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Giáo dục đại cương',
      maMH: 'BAA00104',
      tenMH: 'Lịch sử Đảng Cộng sản Việt Nam',
      soTinChi: 2,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Kiến thức tốt nghiệp',
      maMH: 'CS12111',
      tenMH: 'Quản trị cơ sở dữ liệu hiện đại',
      soTinChi: 4,
      maCN: 1,
      tenCN: 'Hệ thống thông tin',
    },
    {
      loaiMonHoc: 'Kiến thức cơ sở ngành',
      maMH: 'CSC00004',
      tenMH: 'Nhập môn Công nghệ thông tin',
      soTinChi: 4,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Kiến thức tự chọn',
      maMH: 'CSC00008',
      tenMH: 'Lý thuyết đồ thị',
      soTinChi: 4,
      maCN: 9,
      tenCN: 'Công nghệ thông tin',
    },
    {
      loaiMonHoc: 'Kiến thức cơ sở ngành',
      maMH: 'CSC10001',
      tenMH: 'Nhập môn lập trình',
      soTinChi: 4,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Kiến thức cơ sở ngành',
      maMH: 'CSC10002',
      tenMH: 'Kỹ thuật lập trình',
      soTinChi: 4,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Kiến thức cơ sở ngành',
      maMH: 'CSC10003',
      tenMH: 'Phương pháp lập trình hướng đối tượng',
      soTinChi: 4,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Kiến thức cơ sở ngành',
      maMH: 'CSC10004',
      tenMH: 'Cấu trúc dữ liệu và giải thuật',
      soTinChi: 4,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Kiến thức cơ sở ngành',
      maMH: 'CSC10006',
      tenMH: 'Cơ sở dữ liệu',
      soTinChi: 4,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Kiến thức cơ sở ngành',
      maMH: 'CSC10007',
      tenMH: 'Hệ điều hành',
      soTinChi: 4,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Kiến thức cơ sở ngành',
      maMH: 'CSC10008',
      tenMH: 'Mạng máy tính',
      soTinChi: 4,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Kiến thức cơ sở ngành',
      maMH: 'CSC10009',
      tenMH: 'Hệ thống máy tính',
      soTinChi: 4,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Giáo dục đại cương',
      maMH: 'CSC10101',
      tenMH: 'Kỹ năng mềm',
      soTinChi: 3,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Giáo dục đại cương',
      maMH: 'CSC10102',
      tenMH: 'Kiến tập nghề nghiệp',
      soTinChi: 2,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Giáo dục đại cương',
      maMH: 'CSC10103',
      tenMH: 'Khởi nghiệp',
      soTinChi: 3,
      maCN: null,
      chuyenNganh: null,
    },
    {
      loaiMonHoc: 'Kiến thức tự chọn',
      maMH: 'CSC10104',
      tenMH: 'Quy hoạch tuyến tính',
      soTinChi: 4,
      maCN: 2,
      tenCN: 'Kỹ thuật phần mềm',
    },
    {
      loaiMonHoc: 'Kiến thức tự chọn',
      maMH: 'CSC10105',
      tenMH: 'Nhập môn tư duy thuật toán',
      soTinChi: 4,
      maCN: 2,
      tenCN: 'Kỹ thuật phần mềm',
    },
    {
      loaiMonHoc: 'Kiến thức tự chọn',
      maMH: 'CSC10106',
      tenMH: 'Thuật toán tổ hợp và ứng dụng',
      soTinChi: 4,
      maCN: 2,
      tenCN: 'Kỹ thuật phần mềm',
    },
  ],
};
