export const MOCK_SCHOOL_YEARS = {
  data: [
    {
      maHK: 30,
      hocKy: 3,
      namHocBD: 2022,
    },
    {
      maHK: 25,
      hocKy: 1,
      namHocBD: 2021,
    },
    {
      maHK: 23,
      hocKy: 2,
      namHocBD: 2020,
    },
    {
      maHK: 20,
      hocKy: 2,
      namHocBD: 2019,
    },
    {
      maHK: 16,
      hocKy: 1,
      namHocBD: 2018,
    },
    {
      maHK: 15,
      hocKy: 3,
      namHocBD: 2017,
    },
    {
      maHK: 10,
      hocKy: 1,
      namHocBD: 2016,
    },
    {
      maHK: 9,
      hocKy: 3,
      namHocBD: 2015,
    },
    {
      maHK: 6,
      hocKy: 3,
      namHocBD: 2014,
    },
    {
      maHK: 3,
      hocKy: 3,
      namHocBD: 2013,
    },
  ],
};

export const MOCK_TRAINING_POINT_DATA = {
  page: 1,
  size: 25,
  lastPage: 1,
  total: 6,
  data: [
    {
      xepLoai: 'Xuất sắc',
      drl: 1,
      maSV: '19127107',
      tenSV: 'Nguyễn Thu Thảo Châu',
      maSH: '19CLC3',
      maHK: 19,
      hocKy: 1,
      namHocBD: 2019,
    },
    {
      xepLoai: 'Xuất sắc',
      drl: 2,
      maSV: '19127268',
      tenSV: 'Nguyễn Ngọc Thanh Tâm',
      maSH: '19CLC2',
      maHK: 19,
      hocKy: 1,
      namHocBD: 2019,
    },
    {
      xepLoai: 'Xuất sắc',
      drl: 90,
      maSV: '19127511',
      tenSV: 'La Ngọc Hồng Phúc',
      maSH: '19CLC5',
      maHK: 19,
      hocKy: 1,
      namHocBD: 2019,
    },
    {
      xepLoai: 'Xuất sắc',
      drl: 90,
      maSV: '19127568',
      tenSV: 'Nguyễn Thị Minh Thu',
      maSH: '19CLC5',
      maHK: 19,
      hocKy: 1,
      namHocBD: 2019,
    },
    {
      xepLoai: 'Xuất sắc',
      drl: 10,
      maSV: '19127569',
      tenSV: 'Nguyễn Huy Anh Thư',
      maSH: '19CLC10',
      maHK: 19,
      hocKy: 1,
      namHocBD: 2019,
    },
    {
      xepLoai: 'Xuất sắc',
      drl: 95,
      maSV: '19127189',
      tenSV: 'Hồ Lâm Bảo Khuyên',
      maSH: '19CLC3',
      maHK: 20,
      hocKy: 2,
      namHocBD: 2019,
    },
  ],
};
